### ISSUE TITLE
Missing BPL Artwork

### ISSUE THREAD

**Issue by billotronic** [blockpool-io/BPL-desktop#11]
for cooking (all?) distributable packages, artwork from here:: 

https://github.com/blockpool-io/BPL-desktop/tree/master/build

are used but are still ark artwork

http://imgur.com/a/V8INW

**Comment by cyrus19901** [comment]
Thanks for pointing that out. I thought that was taken care but i will update the same today

**Comment by billotronic** [comment]
You are very much welcome.

**Comment by cyrus19901** [comment]
This has been solved. Thanks billotronic
