### ISSUE TITLE
Last release still shows that there is new version

### ISSUE THREAD

**Issue by biolypl** [blockpool-io/BPL-desktop#16]
I use latest 1.2.2 release for Windows 64, unfortunately I still see message "New version available"

**Comment by cyrus19901** [comment]
Did you download that from https://blockpool.io/BPL_Wallet.html ?

**Comment by biolypl** [comment]
Yes, few minutes ago

**Comment by cyrus19901** [comment]
Hmmm...well i guess i disabled that.But i will look into it.However we are working on a different wallet right now so that might be released soon.

**Comment by cyrus19901** [comment]
This has been solved in the develop branch. We will be releasing the build version for different platforms soon .
