### ISSUE TITLE
I can't register delegate

### ISSUE THREAD

**Issue by biolypl** [blockpool-io/BPL-desktop#17]
I try to register delegate "bioly" but get this error message:
![ann](https://user-images.githubusercontent.com/19519175/31254796-6f37cbfc-aa2a-11e7-82a2-d9263a27c655.png)

**Comment by cyrus19901** [comment]
Are you using special characters for your delegate name ?

**Comment by biolypl** [comment]
Of course not, I try to register "bioly"

**Comment by cyrus19901** [comment]
hmmm...i have never encountered that problem and neither has anyone else. Can you try with some other name ?

**Comment by biolypl** [comment]
Strange, I've successful registered "biobpl" but with "bioly" I have the same issue.

**Comment by cyrus19901** [comment]
Interesting! Thanks for pointing that out. I will look at it tonight and get back to you on that
